### ISSUE TITLE
TODO - Original

### ISSUE THREAD

**Issue by jamesjmeyer210** [James-Shawn/coffee-project#1]
- [x] Update the html

- [x] Tables are a little old school, you need to refactor the code so that each coffee is displayed in a div that contains a heading displaying the coffee name, and the type of roast in a paragraph. Don't display the ids, these are only for our application's internal use

- [x] When the page loads, the coffees should be sorted by their ids in ascending order

- [x] Add functionality to search through the coffees by name, and display only the coffees that match the provided search term (You will need to add an input field to the existing form for this)

- [x] Add functionality to update the displayed coffee as the user types into the search box, or as soon as they select an option from the select

**Comment by jamesjmeyer210** [comment]
# CSS
- [x] remove bullets from ul and li
- [x] apply css to the following classes:
    - [x] coffee-item
    - [x] coffee-item-name
    - [x] coffee-item-roast

**Comment by jamesjmeyer210** [comment]
# CSS For Columns

- [x] use javascript to print a random distribution of columns in the *renderCoffeeItem(...)* function". That way, every time they refresh, there are a different distribution of css items.

**Comment by jamesjmeyer210** [comment]
# Javascript Functions

- [ ] We need a function that takes in "input" and returns true if it is only letters || false if it has numbers and other characters. Use a loop, and check each character of the string against the characters in the ASCII table
- [x] We need a search function that makes new coffee objects and adds them to the "coffees" list
- [x] We need a function to search the "coffees" and return a sublist of results

**Comment by jamesjmeyer210** [comment]
# HTML Reset
- [x] When the page loads, the text fields and drop down menus ought to be cleared
- [x] Once the text fields and drop down menus are cleared, we can init the "dropdownSelectState" object to "All" and "Light Roast"

**Comment by jamesjmeyer210** [comment]
# Javascript Refractoring

- [x] Move the global variables to the top of the main.js
- [x] Ensure the sequence and order of all the functions is reasonable
